name: CI Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        required: true
        default: 'development'
        options:
          - development
          - testing
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development' || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Development
        run: echo 'Deploying to Development'

  deploy-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'testing' || github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Testing
        run: echo 'Deploying to Testing'